-- Generated by Home Manager.
-- See https://wiki.hypr.land/Configuring/Start/

-- settings.curve
hl.curve("fast-stiff", {
  ["dampening"] = 50,
  ["mass"] = 1,
  ["stiffness"] = 700,
  ["type"] = "spring"
})

-- settings.animation
hl.animation({
  ["enabled"] = true,
  ["leaf"] = "global",
  ["speed"] = 1,
  ["spring"] = "fast-stiff"
})
hl.animation({
  ["enabled"] = true,
  ["leaf"] = "windows",
  ["speed"] = 1,
  ["spring"] = "fast-stiff"
})
hl.animation({
  ["enabled"] = true,
  ["leaf"] = "windowsOut",
  ["speed"] = 1,
  ["spring"] = "fast-stiff",
  ["style"] = "popin 80%"
})
hl.animation({
  ["enabled"] = true,
  ["leaf"] = "fade",
  ["speed"] = 1,
  ["spring"] = "fast-stiff"
})
hl.animation({
  ["enabled"] = true,
  ["leaf"] = "workspaces",
  ["speed"] = 1,
  ["spring"] = "fast-stiff",
  ["style"] = "slidefadevert 20%"
})
hl.animation({
  ["enabled"] = true,
  ["leaf"] = "specialWorkspace",
  ["speed"] = 1,
  ["spring"] = "fast-stiff",
  ["style"] = "fade"
})
hl.animation({
  ["enabled"] = false,
  ["leaf"] = "layers"
})
hl.animation({
  ["enabled"] = false,
  ["leaf"] = "layersIn"
})

-- settings.bind
hl.bind("SUPER + SHIFT + Q", (hl.dsp.exec_cmd("qs ipc call powermenu toggle")))
hl.bind("SUPER + Return", (hl.dsp.exec_cmd("kitty")))
hl.bind("SUPER + B", (hl.dsp.exec_cmd("qs ipc call whichkey toggle browser")))
hl.bind("SUPER + SHIFT + C", (hl.dsp.exec_cmd("qs ipc call whichkey toggle window")))
hl.bind("SUPER + F", (hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" })))
hl.bind("SUPER + SHIFT + F", (hl.dsp.window.fullscreen()))
hl.bind("SUPER + P", (hl.dsp.window.pin()))
hl.bind("SUPER + V", (hl.dsp.window.float()))
hl.bind("SUPER + Q", (hl.dsp.exec_cmd("qs ipc call whichkey toggle bar")))
hl.bind("SUPER + Space", (hl.dsp.exec_cmd("qs ipc call launcher toggle; hyprctl switchxkblayout current 0")))
hl.bind("SUPER + SHIFT + Space", (hl.dsp.exec_cmd("qs ipc call run toggle; hyprctl switchxkblayout current 0")))
hl.bind("SUPER + SHIFT + comma", (hl.dsp.workspace.move({ monitor = "+1" })))
hl.bind("SUPER + SHIFT + V", (hl.dsp.exec_cmd("qs ipc call cliphist toggle; hyprctl switchxkblayout current 0")))
hl.bind("SUPER + SHIFT + P", (hl.dsp.exec_cmd("qs ipc call whichkey toggle picker; hyprctl switchxkblayout current 0")))
hl.bind("Print", (hl.dsp.exec_cmd("qs ipc call whichkey toggle screen")))
hl.bind("SUPER + A", (hl.dsp.focus({ direction = "up" })))
hl.bind("SUPER + H", (hl.dsp.focus({ direction = "down" })))
hl.bind("SUPER + Up", (hl.dsp.focus({ direction = "up" })))
hl.bind("SUPER + Down", (hl.dsp.focus({ direction = "down" })))
hl.bind("SUPER + bracketright", (hl.dsp.window.move({ direction = "right" })))
hl.bind("SUPER + bracketleft", (hl.dsp.window.move({ direction = "left" })))
hl.bind("SUPER + SHIFT + A", (hl.dsp.window.move({ direction = "up" })))
hl.bind("SUPER + SHIFT + H", (hl.dsp.window.move({ direction = "down" })))
hl.bind("SUPER + SHIFT + Up", (hl.dsp.window.move({ direction = "up" })))
hl.bind("SUPER + SHIFT + Down", (hl.dsp.window.move({ direction = "down" })))
hl.bind("SUPER + N", (hl.dsp.exec_cmd("qs ipc call notifications dismissOldestPopup")))
hl.bind("SUPER + SHIFT + N", (hl.dsp.exec_cmd("qs ipc call notifications dismissAllPopups")))
hl.bind("SUPER + S", (hl.dsp.workspace.toggle_special("")))
hl.bind("SUPER + SHIFT + S", (hl.dsp.window.move({ workspace = "special" })))
hl.bind("SUPER + mouse:272", (hl.dsp.window.drag()), {
  ["mouse"] = true
})
hl.bind("SUPER + mouse:273", (hl.dsp.window.resize()), {
  ["mouse"] = true
})
hl.bind("XF86AudioRaiseVolume", (hl.dsp.exec_cmd("wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+")), {
  ["locked"] = true,
  ["repeating"] = true
})
hl.bind("XF86AudioLowerVolume", (hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-")), {
  ["locked"] = true,
  ["repeating"] = true
})
hl.bind("SHIFT + XF86AudioRaiseVolume", (hl.dsp.exec_cmd("wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SOURCE@ 5%+")), {
  ["locked"] = true,
  ["repeating"] = true
})
hl.bind("SHIFT + XF86AudioLowerVolume", (hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SOURCE@ 5%-")), {
  ["locked"] = true,
  ["repeating"] = true
})
hl.bind("XF86AudioMute", (hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle")), {
  ["locked"] = true
})
hl.bind("SHIFT + XF86AudioMute", (hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle")), {
  ["locked"] = true
})
hl.bind("XF86AudioMicMute", (hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle")), {
  ["locked"] = true
})
hl.bind("XF86MonBrightnessDown", (hl.dsp.exec_cmd("hyprctl hyprsunset gamma -10; qs ipc call osd brightness")), {
  ["locked"] = true,
  ["repeating"] = true
})
hl.bind("XF86MonBrightnessUp", (hl.dsp.exec_cmd("hyprctl hyprsunset gamma +10; qs ipc call osd brightness")), {
  ["locked"] = true,
  ["repeating"] = true
})
hl.bind("XF86AudioPlay", (hl.dsp.exec_cmd("playerctl play-pause")), {
  ["locked"] = true
})
hl.bind("XF86AudioNext", (hl.dsp.exec_cmd("playerctl next")), {
  ["locked"] = true
})
hl.bind("XF86AudioPrev", (hl.dsp.exec_cmd("playerctl previous")), {
  ["locked"] = true
})
hl.bind("switch:on:Lid Switch", (hl.dsp.exec_cmd([[hyprctl keyword monitor "eDP-1,disable"]])), {
  ["locked"] = true
})
hl.bind("switch:off:Lid Switch", (hl.dsp.exec_cmd([[hyprctl keyword monitor "eDP-1,1920x1200,0x0,1.2"]])), {
  ["locked"] = true
})
hl.bind("SUPER + Tab", (function()
  hl.dispatch(hl.dsp.window.cycle_next())
  hl.dispatch(hl.dsp.window.bring_to_top())
end
))
hl.bind("SUPER + R", (function()
  if hl.get_active_window().fullscreen == 1 then
    hl.dispatch(hl.dsp.window.fullscreen({ mode = "maximized", action = "unset" }))
  elseif hl.get_active_window().fullscreen == 2 then
    hl.dispatch(hl.dsp.window.fullscreen({ action = "unset" }))
  else
    hl.dispatch(hl.dsp.layout("colresize +conf"))
  end
end
))
hl.bind("SUPER + SHIFT + E", (function()
  if hl.get_active_window().floating then
    hl.dispatch(hl.dsp.window.move({ direction = "right" }))
  else
    hl.dispatch(hl.dsp.layout("swapcol r"))
  end
end
))
hl.bind("SUPER + SHIFT + Y", (function()
  if hl.get_active_window().floating then
    hl.dispatch(hl.dsp.window.move({ direction = "left" }))
  else
    hl.dispatch(hl.dsp.layout("swapcol l"))
  end
end
))
hl.bind("SUPER + E", (hl.dsp.layout("focus r")))
hl.bind("SUPER + Y", (hl.dsp.layout("focus l")))
hl.bind("SUPER + SHIFT + Right", (function()
  if hl.get_active_window().floating then
    hl.dispatch(hl.dsp.window.move({ direction = "right" }))
  else
    hl.dispatch(hl.dsp.layout("swapcol r"))
  end
end
))
hl.bind("SUPER + SHIFT + Left", (function()
  if hl.get_active_window().floating then
    hl.dispatch(hl.dsp.window.move({ direction = "left" }))
  else
    hl.dispatch(hl.dsp.layout("swapcol l"))
  end
end
))
hl.bind("SUPER + Right", (hl.dsp.layout("focus r")))
hl.bind("SUPER + Left", (hl.dsp.layout("focus l")))
hl.bind("SUPER + C", (function()
  local win = hl.get_active_window()
  hl.config({ scrolling = { focus_fit_method = 0 } })
  hl.dispatch(hl.dsp.focus({ window = win }))
  hl.config({ scrolling = { focus_fit_method = 1 } })
end
))
hl.bind("SUPER + SHIFT + R", (hl.dsp.submap("resize")))
hl.bind("SUPER + M", (hl.dsp.submap("move")))
hl.bind("SUPER + code:10", (hl.dsp.focus({ workspace = 1 })))
hl.bind("SUPER + SHIFT + code:10", (hl.dsp.window.move({ workspace = 1 })))
hl.bind("SUPER + code:11", (hl.dsp.focus({ workspace = 2 })))
hl.bind("SUPER + SHIFT + code:11", (hl.dsp.window.move({ workspace = 2 })))
hl.bind("SUPER + code:12", (hl.dsp.focus({ workspace = 3 })))
hl.bind("SUPER + SHIFT + code:12", (hl.dsp.window.move({ workspace = 3 })))
hl.bind("SUPER + code:13", (hl.dsp.focus({ workspace = 4 })))
hl.bind("SUPER + SHIFT + code:13", (hl.dsp.window.move({ workspace = 4 })))
hl.bind("SUPER + code:14", (hl.dsp.focus({ workspace = 5 })))
hl.bind("SUPER + SHIFT + code:14", (hl.dsp.window.move({ workspace = 5 })))
hl.bind("SUPER + code:15", (hl.dsp.focus({ workspace = 6 })))
hl.bind("SUPER + SHIFT + code:15", (hl.dsp.window.move({ workspace = 6 })))
hl.bind("SUPER + code:16", (hl.dsp.focus({ workspace = 7 })))
hl.bind("SUPER + SHIFT + code:16", (hl.dsp.window.move({ workspace = 7 })))
hl.bind("SUPER + code:17", (hl.dsp.focus({ workspace = 8 })))
hl.bind("SUPER + SHIFT + code:17", (hl.dsp.window.move({ workspace = 8 })))
hl.bind("SUPER + code:18", (hl.dsp.focus({ workspace = 9 })))
hl.bind("SUPER + SHIFT + code:18", (hl.dsp.window.move({ workspace = 9 })))
hl.bind("SUPER + code:19", (hl.dsp.focus({ workspace = 10 })))
hl.bind("SUPER + SHIFT + code:19", (hl.dsp.window.move({ workspace = 10 })))

-- settings.config
hl.config({
  ["animations"] = {
    ["enabled"] = true
  },
  ["binds"] = {
    ["allow_pin_fullscreen"] = true
  },
  ["cursor"] = {
    ["inactive_timeout"] = 20
  },
  ["debug"] = {
    ["disable_logs"] = false
  },
  ["decoration"] = {
    ["active_opacity"] = 0.9,
    ["blur"] = {
      ["passes"] = 3,
      ["size"] = 2
    },
    ["fullscreen_opacity"] = 0.9,
    ["inactive_opacity"] = 0.85,
    ["shadow"] = {
      ["range"] = 4
    }
  },
  ["ecosystem"] = {
    ["no_donation_nag"] = true
  },
  ["general"] = {
    ["allow_tearing"] = false,
    ["border_size"] = 2,
    ["gaps_out"] = 15,
    ["layout"] = "scrolling",
    ["resize_on_border"] = false
  },
  ["input"] = {
    ["kb_layout"] = "us,ua-graph-rev",
    ["kb_options"] = "grp:caps_toggle",
    ["repeat_delay"] = 250,
    ["sensitivity"] = -0.2,
    ["touchpad"] = {
      ["natural_scroll"] = true,
      ["scroll_factor"] = 0.2
    }
  },
  ["misc"] = {
    ["animate_manual_resizes"] = true,
    ["animate_mouse_windowdragging"] = true,
    ["disable_hyprland_logo"] = true,
    ["disable_splash_rendering"] = true,
    ["key_press_enables_dpms"] = true,
    ["mouse_move_enables_dpms"] = true,
    ["on_focus_under_fullscreen"] = 2
  },
  ["render"] = {
    ["expand_undersized_textures"] = false
  },
  ["scrolling"] = {
    ["explicit_column_widths"] = "0.32833, 0.4925, 0.6566",
    ["follow_min_visible"] = 0.99
  },
  ["xwayland"] = {
    ["force_zero_scaling"] = true
  }
})

-- settings.env
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("WLR_DRM_NO_ATOMIC", "1")
hl.env("EDITOR", "nvim")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("AWWW_TRANSITION", "random")
hl.env("AWWW_TRANSITION_FPS", "120")

-- settings.monitor
-- hl.monitor({
--   ["mode"] = "1920x1200",
--   ["output"] = "eDP-1",
--   ["position"] = "0x0",
--   ["scale"] = 1.2
-- })
-- hl.monitor({
--   ["mode"] = "3440x1440@100Hz",
--   ["output"] = "desc:Xiaomi Corporation Mi Monitor",
--   ["position"] = "1600x-50",
--   ["scale"] = "auto"
-- })

-- settings.on
hl.on("hyprland.start", (function ()
  hl.exec_cmd("dbus-update-activation-environment --all --systemd")
  hl.exec_cmd("hyprland-per-window-layout")
  hl.exec_cmd("udiskie & awww-daemon")
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("quickshell")
  hl.exec_cmd("sleep 1; matugen image \"$(find ~/Pictures/wallpapers -type f,l | shuf -n 1)\" --source-color-index 0")
  hl.exec_cmd("Telegram")
  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("wl-paste --type image --watch cliphist store")
  hl.exec_cmd("wl-clip-persist --clipboard regular")
  -- hl.exec_cmd("rm \"$HOME/.cache/cliphist/db\"")
  hl.exec_cmd("brightnessctl -s set 50%")
  hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
  -- hl.exec_cmd("pkill kanshi; kanshi")
end
))
hl.on("window.active", (function (window, reason)
  if reason == 1 then
    hl.timer(function()
      if window.address == hl.get_active_window().address then
        hl.dispatch(hl.dsp.layout("fit_into_view"))
      end
    end, { timeout = 1000, type = "oneshot" })
  end
end
))

-- settings.window_rule
hl.window_rule({
  ["match"] = {
    ["class"] = ".*"
  },
  ["name"] = "suppress-maximize-events",
  ["suppress_event"] = "maximize"
})
hl.window_rule({
  ["match"] = {
    ["class"] = "[lL]ibrewolf"
  },
  ["name"] = "librewolf-workspace",
  ["opacity"] = "1 override",
  ["scrolling_width"] = 0.7,
  ["workspace"] = "1"
})
hl.window_rule({
  ["match"] = {
    ["class"] = "kitty"
  },
  ["name"] = "kitty-workspace",
  ["workspace"] = "2"
})
hl.window_rule({
  ["match"] = {
    ["class"] = "[cC]hromium.*"
  },
  ["name"] = "chromium-workspace",
  ["opacity"] = "1 override",
  ["scrolling_width"] = 0.7,
  ["workspace"] = "3"
})
hl.window_rule({
  ["match"] = {
    ["class"] = "org.telegram.desktop",
    ["initial_title"] = "^Telegram.*$"
  },
  ["name"] = "telegram-workspace",
  ["tag"] = "+chat"
})
hl.window_rule({
  ["match"] = {
    ["class"] = "[sS]lack"
  },
  ["name"] = "slack-workspace",
  ["tag"] = "+chat"
})
hl.window_rule({
  ["match"] = {
    ["class"] = "jetbrains-.*",
    ["float"] = false
  },
  ["name"] = "jetbrains-workspace",
  ["scrolling_width"] = 1,
  ["workspace"] = "5"
})
hl.window_rule({
  ["match"] = {
    ["class"] = "teams-for-linux"
  },
  ["name"] = "teams-workspace",
  ["opacity"] = "1 override",
  ["scrolling_width"] = 0.7,
  ["workspace"] = "6"
})
hl.window_rule({
  ["match"] = {
    ["class"] = "orca-slicer",
    ["float"] = false
  },
  ["name"] = "orcaslicer-workspace",
  ["tag"] = "+cad"
})
hl.window_rule({
  ["match"] = {
    ["class"] = "org.freecad.FreeCAD",
    ["float"] = false
  },
  ["name"] = "freecad-workspace",
  ["tag"] = "+cad"
})
hl.window_rule({
  ["match"] = {
    ["class"] = "steam"
  },
  ["name"] = "steam-workspace",
  ["opacity"] = "1 override",
  ["workspace"] = "9"
})
hl.window_rule({
  ["match"] = {
    ["class"] = "[sS]potify"
  },
  ["name"] = "spotify-workspace",
  ["workspace"] = "10"
})
hl.window_rule({
  ["match"] = {
    ["class"] = "xdg-desktop-portal-gtk",
    ["initial_title"] = "All Files"
  },
  ["name"] = "portal-file-dialog",
  ["tag"] = "+file-picker"
})
hl.window_rule({
  ["match"] = {
    ["initial_class"] = "[cC]hromium.*",
    ["initial_title"] = "Save File"
  },
  ["name"] = "chromium-save-file",
  ["tag"] = "+file-picker"
})
hl.window_rule({
  ["match"] = {
    ["initial_class"] = "[cC]hromium.*",
    ["initial_title"] = "Open File"
  },
  ["name"] = "chromium-open-file",
  ["tag"] = "+file-picker"
})
hl.window_rule({
  ["match"] = {
    ["initial_class"] = "[cC]hromium.*",
    ["initial_title"] = "Open Files"
  },
  ["name"] = "chromium-open-files",
  ["tag"] = "+file-picker"
})
hl.window_rule({
  ["center"] = true,
  ["float"] = true,
  ["match"] = {
    ["class"] = "org.gnome.Loupe"
  },
  ["name"] = "loupe-float",
  ["size"] = "(monitor_w*0.6) (monitor_h*0.8)"
})
hl.window_rule({
  ["match"] = {
    ["class"] = "org.telegram.desktop",
    ["initial_title"] = "^Telegram.*$"
  },
  ["name"] = "telegram-opacity",
  ["no_screen_share"] = true,
  ["opacity"] = "0.95 override 0.9 override 0.95 override"
})
hl.window_rule({
  ["float"] = true,
  ["fullscreen"] = true,
  ["match"] = {
    ["initial_class"] = "org.telegram.desktop",
    ["initial_title"] = "Media viewer"
  },
  ["name"] = "telegram-media-fs-opacity",
  ["opacity"] = "1 override"
})
hl.window_rule({
  ["float"] = true,
  ["match"] = {
    ["initial_class"] = "org.telegram.desktop",
    ["initial_title"] = "TelegramDesktop"
  },
  ["name"] = "telegram-media-opacity",
  ["opacity"] = "1 override"
})
hl.window_rule({
  ["match"] = {
    ["class"] = ".*",
    ["workspace"] = "8"
  },
  ["name"] = "sharing-ws-opacity",
  ["opacity"] = "1 override"
})
hl.window_rule({
  ["match"] = {
    ["class"] = "thunar"
  },
  ["name"] = "thunar-opacity",
  ["opacity"] = "0.9"
})
hl.window_rule({
  ["center"] = true,
  ["float"] = true,
  ["match"] = {
    ["class"] = "org.pulseaudio.pavucontrol"
  },
  ["name"] = "pavucontrol-float",
  ["opacity"] = "0.85",
  ["size"] = "monitor_w*0.3 monitor_h*0.8"
})
hl.window_rule({
  ["center"] = true,
  ["float"] = true,
  ["match"] = {
    ["class"] = "com.gabm.satty"
  },
  ["name"] = "satty-float"
})
hl.window_rule({
  ["match"] = {
    ["class"] = "[sS]potify"
  },
  ["name"] = "spotify-opacity",
  ["opacity"] = "0.9 override"
})
hl.window_rule({
  ["center"] = true,
  ["float"] = true,
  ["match"] = {
    ["class"] = "thunar",
    ["title"] = "File Operation Progress"
  },
  ["name"] = "thunar-progress-float"
})
hl.window_rule({
  ["float"] = true,
  ["keep_aspect_ratio"] = true,
  ["match"] = {
    ["title"] = "Picture[- ]in[- ]?[Pp]icture"
  },
  ["move"] = "monitor_w-970 monitor_h-550",
  ["name"] = "picture-in-picture",
  ["no_initial_focus"] = true,
  ["pin"] = true,
  ["size"] = "960 540"
})
hl.window_rule({
  ["float"] = true,
  ["match"] = {
    ["class"] = "jetbrains-.*"
  },
  ["name"] = "jetbrains-popups",
  ["no_follow_mouse"] = true,
  ["no_initial_focus"] = true
})
hl.window_rule({
  ["match"] = {
    ["class"] = "steam_app_881100"
  },
  ["name"] = "noita-immediate",
  ["tag"] = "+game"
})
hl.window_rule({
  ["float"] = true,
  ["keep_aspect_ratio"] = true,
  ["match"] = {
    ["class"] = "teams-for-linux",
    ["initial_title"] = ".* Screen is being shared"
  },
  ["move"] = "monitor_w-970 monitor_h-550",
  ["name"] = "teams-windows",
  ["no_initial_focus"] = true,
  ["size"] = "960 540"
})
hl.window_rule({
  ["center"] = true,
  ["float"] = true,
  ["match"] = {
    ["initial_title"] = "Select what to share"
  },
  ["name"] = "sharepicker"
})
hl.window_rule({
  ["match"] = {
    ["tag"] = "chat"
  },
  ["name"] = "chatting-ws",
  ["workspace"] = "4"
})
hl.window_rule({
  ["match"] = {
    ["tag"] = "cad"
  },
  ["name"] = "cad-ws",
  ["opacity"] = "1 override",
  ["scrolling_width"] = 1,
  ["workspace"] = "7"
})
hl.window_rule({
  ["center"] = true,
  ["float"] = true,
  ["match"] = {
    ["tag"] = "file-picker"
  },
  ["name"] = "picker-layout",
  ["size"] = "(monitor_w*0.5) (monitor_h*0.8)"
})
hl.window_rule({
  ["immediate"] = true,
  ["match"] = {
    ["tag"] = "game"
  },
  ["name"] = "game-tearing"
})

-- settings.workspace_rule
hl.workspace_rule({
  ["gaps_in"] = 30,
  ["gaps_out"] = 50,
  ["workspace"] = "s[true]"
})

-- submaps.move
hl.define_submap("move", function()
  hl.bind("E", (hl.dsp.window.move({ x = 30, y = 0, relative = true })), {
    ["repeating"] = true
  })
  hl.bind("Y", (hl.dsp.window.move({ x = -30, y = 0, relative = true })), {
    ["repeating"] = true
  })
  hl.bind("H", (hl.dsp.window.move({ x = 0, y = 30, relative = true })), {
    ["repeating"] = true
  })
  hl.bind("A", (hl.dsp.window.move({ x = 0, y = -30, relative = true })), {
    ["repeating"] = true
  })
  hl.bind("Right", (hl.dsp.window.move({ x = 30, y = 0, relative = true })), {
    ["repeating"] = true
  })
  hl.bind("Left", (hl.dsp.window.move({ x = -30, y = 0, relative = true })), {
    ["repeating"] = true
  })
  hl.bind("Down", (hl.dsp.window.move({ x = 0, y = 30, relative = true })), {
    ["repeating"] = true
  })
  hl.bind("Up", (hl.dsp.window.move({ x = 0, y = -30, relative = true })), {
    ["repeating"] = true
  })
  hl.bind("escape", (hl.dsp.submap("reset")))
end)

-- submaps.resize
hl.define_submap("resize", function()
  hl.bind("E", (hl.dsp.window.resize({ x = 20, y = 0, relative = true })), {
    ["repeating"] = true
  })
  hl.bind("Y", (hl.dsp.window.resize({ x = -20, y = 0, relative = true })), {
    ["repeating"] = true
  })
  hl.bind("H", (hl.dsp.window.resize({ x = 0, y = -20, relative = true })), {
    ["repeating"] = true
  })
  hl.bind("A", (hl.dsp.window.resize({ x = 0, y = 20, relative = true })), {
    ["repeating"] = true
  })
  hl.bind("Right", (hl.dsp.window.resize({ x = 20, y = 0, relative = true })), {
    ["repeating"] = true
  })
  hl.bind("Left", (hl.dsp.window.resize({ x = -20, y = 0, relative = true })), {
    ["repeating"] = true
  })
  hl.bind("Down", (hl.dsp.window.resize({ x = 0, y = -20, relative = true })), {
    ["repeating"] = true
  })
  hl.bind("Up", (hl.dsp.window.resize({ x = 0, y = 20, relative = true })), {
    ["repeating"] = true
  })
  hl.bind("escape", (hl.dsp.submap("reset")))
end)

-- startup
-- hl.on("hyprland.start", function()
--   hl.exec_cmd("/nix/store/2swbxihjql78pnn5kfmhjq5dvp9m744b-dbus-1.16.2/bin/dbus-update-activation-environment --systemd --all && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target")
-- end)

-- shutdown
hl.on("hyprland.shutdown", function()
  os.execute("systemctl --user stop hyprland-session.target && sleep 0.1")
end)


-- extraConfig
local config_home = os.getenv("XDG_CONFIG_HOME") or (os.getenv("HOME") .. "/.config")
package.path = config_home .. "/hypr/?.lua;" .. package.path
local colors = require "colors"
hl.config({
  general = {
    col = {
      active_border = { colors = { "rgba(" .. colors.primary .. "ee)", "rgba(" .. colors.secondary .. "ee)" }, angle = 45 },
      inactive_border = "rgba(" .. colors.background .. "aa)",
    },
  },
})

